definitions:
  handler.request:
    properties:
      count:
        type: integer
      name:
        type: string
      price:
        type: number
      type:
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data:
        type: any
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.br/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.br/pt_br/termos-e-condicoes
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /produtos:
    get:
      consumes:
      - application/json
      description: Lista todos os produtos no banco de dados do Meli
      parameters:
      - description: Token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Listar todos os produtos
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Adiciona um novo produto ao banco de dados do Meli
      parameters:
      - description: Token
        in: header
        name: token
        required: true
        type: string
      - description: Product to store
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
      summary: Adicionar um novo produto
      tags:
      - Products
  /produtos/{id}:
    delete:
      consumes:
      - application/json
      description: Deletar um produto do banco de dados do Meli
      parameters:
      - description: Token
        in: header
        name: token
        required: true
        type: string
      - description: Product ID to Delete
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Deletar um produto
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Atualizar o nome de um produto existente no banco de dados do Meli
      parameters:
      - description: Token
        in: header
        name: token
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product to Patch
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Trocar o nome de um produto
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Atualizar um produto que já esta no banco de dados do Meli
      parameters:
      - description: Token
        in: header
        name: token
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product to Update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Substituir um produto
      tags:
      - Products
swagger: "2.0"
